### ISSUE TITLE
Add a test runner to run tests for multiple components

### ISSUE THREAD

**Issue by alaminopu** [totaljs/flowstreamcomponents#11]
Right now, we can only run one component test at a time. Example:  `node tests/counter.js`

It would be great to have a test runner, so can run multiple components test file at a time. 

Simplest solution would be - 

```javascript
const files = process.argv.slice(2);

const cp = require("child_process");

// Load each file using `require`
files.forEach((file) => {
  cp.fork(file);
});
```

Then we can run multiple components test with - `node test-runner.js ./tests/*.test.js`

In addition, it would be nice to collect all the stats from all the test and then show it all together.

**Comment by petersirka** [comment]
Added: https://github.com/totaljs/flowstreamcomponents/commit/42991f9c0002483fbba044615a10b91357440098
More info: <https://github.com/totaljs/flowstreamcomponents#run-unit-test-for-all-tests>
