### ISSUE TITLE
MongoDB Query Send Bug

### ISSUE THREAD

**Issue by ColtonMcInroy** [totaljs/flowstreamcomponents#27]
The MongoDB Query Component [on line 48](https://github.com/totaljs/flowstreamcomponents/blob/main/components/mongodb-query.html#L48) has what seems like a bug to me. Currently it executes instance.send() rather than $.send(). This results in the message being sent but as a clone by the looks of it because although the message sends, but it never executes an message.on('end') and the message appears to get stuck in a pending status.

**Comment by petersirka** [comment]
@Will-create can you check it?

**Comment by molda** [comment]
That was my mistake. Fixed f8ae6f5618c1b8a3c96b7b6686df7f47e730f22c
Thanks for the report @ColtonMcInroy

**Comment by ColtonMcInroy** [comment]
Thanks, that should do it.
