### ISSUE TITLE
Kafka component request

### ISSUE THREAD

**Issue by xecrom** [totaljs/flowstreamcomponents#29]
Is there any plan to take kafka publisher or consumer component?

**Comment by petersirka** [comment]
Hi @xecrom, yes we plan it. When? I don't know right now, but this year.

**Comment by xecrom** [comment]
Hi @petersirka  Any progress?

**Comment by petersirka** [comment]
Hi @xecrom, ahhh. We have it, but I still have a task in review from @Will-create. I'm sending you components for Consumer and Producer. Please let us know if it works for you.

![20231102-095416](https://github.com/totaljs/flowstreamcomponents/assets/2414252/2b99b7b0-1836-4f17-9b4a-ef3095c92529)

[kafka.zip](https://github.com/totaljs/flowstreamcomponents/files/13236390/kafka.zip)

**Comment by xecrom** [comment]
Thanks alot @petersirka , it works well for me!
