### ISSUE TITLE
Missing css property value

### ISSUE THREAD

**Issue by molda** [totaljs/flowstreamcomponents#3]
Ahoj @petersirka , v komponentě print ti chybí hodnota u tab-size 
`.ui-dark .f-print pre { background-color: #404040; tab-size:  } <---`
Nevím co jsi tam chtěl dát tak to nechám na tobě 👍

**Comment by petersirka** [comment]
Tam je veru chyba, sám neviem čo som tam chcel dať. Možno `2`. Idem to pozrieť a fixnúť. Díkes
