### ISSUE TITLE
Archived Components

### ISSUE THREAD

**Issue by yilativ** [totaljs/flowstreamcomponents#33]
What's the recommendation of how to use components that have been archived? I'm specifically interested in RabbitMQ functionality that was moved into the archived folder. 

I have my guess as to use "create component" and copy and paste.... if that's not the best / recommended way, could I get get your guidance on that please?

Thank you

**Comment by petersirka** [comment]
It's absolutely fine, or you can drag and drop components directly into the Flow editor.

---

Archived components are unmaintained, but they can help someone.

**Comment by yilativ** [comment]
Thank you, will do. It’s working for me with my original mentioned way.

[V F - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=2i9ul4)	[2i9ul4]

On March 13, 2024 at 14:41 GMT, Peter Širka ***@***.***> wrote:

It's absolutely fine, or you can drag and drop components directly into the Flow editor.
---------------------------------------------------------------

Archived components are unmaintained, but they can help someone.

**Comment by yilativ** [comment]
Perfect! Thank you
